---
title: "Visualization datasets"
author: "Almut Lütge"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
  sce_name:
  sce:
  meta:
  out:
output:
  html_document:
    self_contained: no
    lib_dir: '../../docs/site_libs'
    code_folding: hide
    theme: journal
    highlight: tango
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: true
    collapsed: no
    smooth_scroll: yes
---


```{r libraries, warning=FALSE}
suppressPackageStartupMessages({
  library(CellMixS)
  library(purrr)
  library(tidyr)
  library(dplyr)
  library(gridExtra)
  library(scran)
  library(cowplot)
  library(jcolors)
  library(ggpubr)
  library(circlize)
  library(viridis)
   library(magrittr)
  library(colorspace)
   library(hrbrthemes)
    library(cowplot)
})

options(bitmapType='cairo')
```


### Dataset and metrics
```{r data}
sce_name <- unlist(c(strsplit(params$sce_name, ",")))

sce_vec <- c(paste0(params$sce, "norm_", sce_name, ".rds"))
names(sce_vec) <- sce_name

meta_vec <- c(paste0(params$meta, sce_name, "_meta.rds"))
names(meta_vec) <- sce_name

out_path <- params$out

cols_data <-c(c(jcolors('pal6'),jcolors('pal8'))[c(1,8,14,5,2:4,6,7,9:13,15:20)],jcolors('pal4'))
names(cols_data) <- c()

cols <-c(c(jcolors('pal6'),jcolors('pal8'), jcolors('pal7'))[c(1,12,18,25,27,2,4,7,3,6,8,14,9,20)],jcolors('pal4'))
names(cols) <- c()
```

```{r vis, fig.width=18, fig.height=24}

plot_fun <- function(sce_nam){
    gc()
    sce <- readRDS(sce_vec[[sce_nam]])
    meta <- readRDS(meta_vec[[sce_nam]])
    tsne <- visGroup(sce, group = meta$batch[[1]]) +
        ggtitle(sce_nam) +
        xlab("tsne1") +
        ylab("tsne2") +
        guides(color = guide_legend(override.aes = list(size = 2, alpha = 1))) +
        theme_ipsum(base_family = 'Helvetica',
                    strip_text_face = "bold",
                    axis_title_size = 22,
                    strip_text_size = 22,
                    plot_margin = margin(0, 0, 0, 0),
                    base_size = 20) +
        theme(
            legend.position="top",
            legend.title = element_blank(),
            plot.title = element_text(size=28, face = "bold"),
            axis.text.x = element_blank(),
            axis.text.y = element_blank(),
            panel.grid.major = element_blank(),
            panel.spacing = unit(1, "lines")
        )
    tsne
}

plot_list <- lapply(sce_name, plot_fun)
p1 <- plot_grid(plot_list[[1]], plot_list[[2]], plot_list[[3]], ncol=3)
p2 <- plot_grid(plot_list[[4]], plot_list[[5]], plot_list[[6]], ncol=3)
p3 <- plot_grid(plot_list[[7]], plot_list[[8]], plot_list[[9]], ncol=3)

p_all <- plot_grid(p1, "", p2, "", p3, ncol= 1, rel_heights = c(1,0.08,1,0.08,1) )#plotlist = plot_list, ncol = 3, labels = c("A", "B", "C", "D", "E", "F", "G", "H", "I"), label_size = 25)


ggsave(filename = paste0(out_path, "vis_all_batches.pdf"), plot = p_all,
       dpi = 600)
```

